import {
  Droplet,
  Leaf,
  Flame,
  Hexagon,
  Pill,
  Wheat,
  ShoppingCart,
  Apple,
  Sparkles,
  Heart,
  Smartphone,
  Shirt,
  UtensilsCrossed,
  Dumbbell,
  Bird,
  type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  "huiles-cosmetiques": Droplet,
  "tisanes-infusions": Leaf,
  "epices-poudres": Flame,
  "miel-ruche": Hexagon,
  "complements-naturels": Pill,
  "cereales-produits-secs": Wheat,
  "alimentation-generale": ShoppingCart,
  "produits-frais": Apple,
  "hygiene-entretien": Sparkles,
  "beaute-soins": Heart,
  "electronique-accessoires": Smartphone,
  "textile-accessoires": Shirt,
  "articles-menagers": UtensilsCrossed,
  "equipements-sportifs": Dumbbell,
  "materiel-elevage": Bird,
};
